inherit_from: .rubocop_todo.yml

# For Rails projects
inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest
  - rubocop-capybara

Metrics/BlockLength:
  Exclude:
    - test/**/*

Minitest/MultipleAssertions:
  Exclude:
    - "test/**/*"

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
